### ISSUE TITLE
Starship multi-line prompt doubles up when line wrapping

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#16]
I think this is an issue with the current implementation of line wrapping and should hopefully be fixed in the refactoring of the very same area in the code that I'm doing right now. @TheLostLambda, I'll ping you to give this another shot once it's done - thanks!

**Comment by TheLostLambda** [comment]
Unfortunately I get a crash now :cry: 
![image](https://user-images.githubusercontent.com/6251883/97807189-4cbb2e00-1c57-11eb-8160-7788b7489d14.png)

**Comment by imsnif** [comment]
Hum... do you think I can reproduce this easily somehow?

**Comment by TheLostLambda** [comment]
Hmm, do you not have the same issue when working with the Starship prompt? I'm happy to do some more debugging later in the week (though the first part of it is quite busy!)

**Comment by imsnif** [comment]
Tbh, I think I had some issue with installing starship and never came back to it. :)
So, @alekspickle said he'd try his hand at this.

**Comment by alekspickle** [comment]
I use konsole and I think I reproduced it with and without starship installed.
I presume it is not even **starship** related. 
I basically just devided window with _ctrl + N_ a few times and voila.
<details>
<summary>with starship</summary>
![Screenshot_20201103_145919](https://user-images.githubusercontent.com/22867443/97989615-760ac400-1de7-11eb-82b8-c83880f2405a.png)
</details> 
<details>
<summary>without starship installed</summary>
![Screenshot_20201103_145919](https://user-images.githubusercontent.com/22867443/97989615-760ac400-1de7-11eb-82b8-c83880f2405a.png)
</details>

**Comment by alekspickle** [comment]
Yeah but I guess first two share at least a way to repoduce.
it is multiple vertical split

**Comment by imsnif** [comment]
Yeah, for sure. I would guess that one has to do with us not limiting the width of new panes. If you feel like working on that, maybe we can open a new issue for it?

**Comment by imsnif** [comment]
Opened a new issue here: https://github.com/mosaic-org/mosaic/issues/21

**Comment by imsnif** [comment]
@TheLostLambda - I think I fixed this. The fix is in main, would you mind confirming when you have the chance?

**Comment by TheLostLambda** [comment]
Hey @imsnif ! Did you fix the crash or the double-line bug? I'm pretty sure I'm still getting the crash on master :cry: I can help do some more proper debugging if you'd like?

**Comment by TheLostLambda** [comment]
Both vertical and horizontal split are crashing for me at the moment with the same: `thread 'screen' panicked at 'fragment out of bounds', src/terminal_pane/scroll.rs:62:80`

**Comment by imsnif** [comment]
Oi, no - I fixed the double line bug. :O 
I must admit I forgot about the crash. :)

So, normal starship prompt works ok but when you split the screen it crashes, or?

**Comment by TheLostLambda** [comment]
It seems to behave as long as I don't split anything or resize the window at least, yeah :)

**Comment by imsnif** [comment]
Right! So let's open a new issue for that. I'll take a look at it. Would you mind doing it? I think it would be easier for you to describe how to reproduce it.

**Comment by TheLostLambda** [comment]
No worries! Can do a bit later this evening :)

**Comment by imsnif** [comment]
Awesome, thanks!
